all: lab9_step2.c lab9_step3.c lab9_step4.c lab9_step5.c
	gcc -o Step2 lab9_step2.c
	gcc -o Step3 lab9_step3.c
	gcc -o Step4 lab9_step4.c
	gcc -o Step5 lab9_step5.c -lpthread
clean:
	rm -f *.out Step2 Step3 Step4 Step5
